version: '3.6'
services:
  postgres:
    image: postgres
    ports:
    - "5555:5555"
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      PGPORT: 5555
  graphql-engine:
    image: hasura/graphql-engine:pull2395-7ea7f82c
    ports:
    - "8888:8888"
    depends_on:
    - "postgres"
    volumes:
    # migration data
    - ./hasura-migrations/migrations:/hasura-migrations
    environment:
      HASURA_GRAPHQL_SERVER_PORT: 8888
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5555/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
